## Overview
Features in the Iris dataset:
– sepal length (cm)
– sepal width (cm)
– petal length (cm)
– petal width (cm)
• Target classes to predict:
– Setosa
– Versicolour
– Virginica

In [1]:
import sklearn 
import numpy as np
import matplotlib
import matplotlib.pyplot as plt

In [2]:
from sklearn import datasets
clf=datasets.load_iris()
x=clf.data  # Samples in iris i.e.150 images
y=clf.target

In [3]:
print(clf.target_names)

['setosa' 'versicolor' 'virginica']


In [4]:
clf.data[11:20]

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3]])

Here 150 images are sliced in 150
150 are then split into train and test
135 for train
15 for test
test_size=0.10  10 % test 90 % 


In [5]:
clf.target[11:20]

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.90, random_state=33)

In [7]:
# create the linear model classifier

from sklearn.svm import SVC
# fit the model
abc=SVC(kernel='rbf')
abc.fit(x_train,y_train)

/home/kiran/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [8]:
y_pred = abc.predict(x_test)

In [9]:
print(x_test)

[[5.7 2.9 4.2 1.3]
 [6.7 3.1 4.4 1.4]
 [4.7 3.2 1.6 0.2]
 [6.5 2.8 4.6 1.5]
 [6.1 2.6 5.6 1.4]
 [6.3 3.3 6.  2.5]
 [4.8 3.4 1.9 0.2]
 [5.1 3.5 1.4 0.3]
 [6.4 3.1 5.5 1.8]
 [6.9 3.2 5.7 2.3]
 [6.8 3.2 5.9 2.3]
 [4.4 3.  1.3 0.2]
 [6.3 3.4 5.6 2.4]
 [6.1 2.9 4.7 1.4]
 [6.9 3.1 5.1 2.3]
 [6.4 2.9 4.3 1.3]
 [6.  3.  4.8 1.8]
 [5.2 3.5 1.5 0.2]
 [6.3 3.3 4.7 1.6]
 [7.2 3.2 6.  1.8]
 [4.9 3.1 1.5 0.1]
 [5.7 3.8 1.7 0.3]
 [6.5 3.  5.8 2.2]
 [4.8 3.  1.4 0.1]
 [6.  2.2 5.  1.5]
 [6.2 2.8 4.8 1.8]
 [6.1 3.  4.6 1.4]
 [6.1 2.8 4.  1.3]
 [6.5 3.  5.2 2. ]
 [5.9 3.  5.1 1.8]
 [5.6 2.7 4.2 1.3]
 [6.7 3.1 4.7 1.5]
 [5.6 2.8 4.9 2. ]
 [6.4 3.2 5.3 2.3]
 [6.7 3.1 5.6 2.4]
 [6.7 3.  5.2 2.3]
 [5.8 2.7 5.1 1.9]
 [5.7 3.  4.2 1.2]
 [5.  2.3 3.3 1. ]
 [4.9 3.1 1.5 0.2]
 [6.3 2.3 4.4 1.3]
 [5.8 2.6 4.  1.2]
 [6.2 2.9 4.3 1.3]
 [4.7 3.2 1.3 0.2]
 [4.6 3.4 1.4 0.3]
 [5.1 2.5 3.  1.1]
 [4.8 3.4 1.6 0.2]
 [7.9 3.8 6.4 2. ]
 [5.1 3.4 1.5 0.2]
 [5.1 3.7 1.5 0.4]
 [5.6 2.9 3.6 1.3]
 [6.5 3.  5.5 1.8]
 [5.4 3.9 1.

In [10]:
print(y_pred)

[1 1 0 1 2 2 0 0 2 2 2 0 2 1 2 1 1 0 1 2 0 0 2 0 1 1 1 1 2 1 1 1 1 2 2 2 2
 1 1 0 1 1 1 0 0 1 0 2 0 0 1 2 0 1 2 2 1 1 0 0 1 0 0 2 1 1 2 2 2 2 0 0 1 1
 0 1 1 1 2 0 2 0 1 0 2 1 0 2 1 0 0 2 0 0 0 2 2 0 1 0 1 0 1 1 1 1 1 0 1 0 1
 2 0 0 0 0 2 2 0 1 1 2 1 0 0 1 1 1 0 1 1 0 2 1 2]


In [11]:
print(x_train.shape)
print(x_test.shape)
print(x_train.shape)
print(x_test.shape)

(15, 4)
(135, 4)
(15, 4)
(135, 4)


In [12]:
y_pred[20]

if (y_pred[20]==0):
    print(clf.target_names[0])
elif(y_pred[20]==1):
    print(clf.target_names[1])
else:
    print(clf.target_names[2])
        

setosa


In [13]:
# Training Accuracy
from sklearn import metrics
y_train_pred = abc.predict(x_train)
print(metrics.accuracy_score(y_train, y_train_pred))

0.9333333333333333


In [14]:
y_pred = abc.predict(x_test)
print (metrics.accuracy_score(y_test, y_pred))

0.9333333333333333


In [15]:
predicted = abc.predict(x_test[0:10])
expected = y_test[0:10]

In [16]:
print(predicted)

[1 1 0 1 2 2 0 0 2 2]


In [17]:
print(expected)

[1 1 0 1 2 2 0 0 2 2]


In [18]:
# Training Accuracy
from sklearn import metrics
y_train_pred = abc.predict(x_train)
print(metrics.accuracy_score(y_train, y_train_pred))

0.9333333333333333


In [20]:
#Testing Accuracy 
y_pred = abc.predict(x_test)
print (metrics.accuracy_score(y_test, y_pred))

0.9333333333333333
